name: Build and test Go projects

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Build
        run: go build -v ./...
        working-directory: ./http_response_hash

      - name: Test
        run: go test -v ./...
        working-directory: ./http_response_hash