name: Learn GitHub Actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  check-bats-version:
    name: Check bats version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  upload-artifact:
    name: Upload artifact (ls workspace)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get ls output
        shell: bash
        run: |
          ls ${{ github.workspace }} > cd_output.log
      - name: Cat output
        shell: bash
        run: |
          cat cd_output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
            name: ls-output-file
            path: cd_output.log
  download-artifact:
    name: Download artifact (ls workspace)
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
            name: ls-output-file
      - name: Cat downloaded artifact
        shell: bash
        run: |
          cat cd_output.log

  outputs-src:
    name: Test outputs (source)
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  outputs-dst:
    name: Test outputs (dest)
    runs-on: ubuntu-latest
    needs: outputs-src
    steps:
      - env:
          OUTPUT1: ${{needs.outputs-src.outputs.output1}}
          OUTPUT2: ${{needs.outputs-src.outputs.output2}}
        run: echo "OUTPUT1:$OUTPUT1 OUTPUT2:$OUTPUT2"

  log-contexts:
    name: Print some contexts
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        run: echo '${{ toJson(github) }}'
      - name: Print job context
        run: echo '${{ toJSON(job) }}'
      - name: Print steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Print runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Print strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Print matrix context
        run: echo '${{ toJSON(matrix) }}'

  action-input-params:
    name: Test actions input params
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        uses: actions/hello_world@main
        with:
          first_name: Mona
          middle_name: The
          last_name: Octocat