name: Learn GitHub Actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    name: Check bats version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  upload-artifact:
    name: Upload artifact (ls workspace)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get ls output
        shell: bash
        run: |
          ls ${{ github.workspace }} > cd_output.log
      - name: Cat output
        shell: bash
        run: |
          cat cd_output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
            name: ls-output-file
            path: cd_output.log
  download-artifact:
    name: Download artifact (ls workspace)
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
            name: ls-output-file
      - name: Cat downloaded artifact
        shell: bash
        run: |
          cat cd_output.log
  log-contexts:
    name: Print some contexts
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        run: echo '${{ toJson(github) }}'
      - name: Print job context
        run: echo '${{ toJSON(job) }}'
      - name: Print steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Print runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Print strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Print matrix context
        run: echo '${{ toJSON(matrix) }}'