name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  upload-artifact:
    name: Upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Get ls output
        shell: bash
        run: |
          ls ${{ github.workspace }} > cd_output.log
      - name: Cat output
        shell: bash
        run: |
          cat cd_output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
            name: ls-output-file
            path: cd_output.log